spring.application.name=notice-zone-backend

spring.datasource.url=jdbc:mysql://localhost:3306/noticezone
spring.datasource.username=root
spring.datasource.password =MySQL@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT config
jwt.secret=h3K5D7knIRUV7qVBNQhCwKIm+/b5vK86rZobU2+/sKUyQ2LFlPEXY4FGMpbxtz2ZyfzwuK69Yw5VnZVzM8xUug==
jwt.expiration=86400000

# Path to store uploaded PDFs
file.upload-dir=uploads
